# Generated by Django 5.2.8 on 2025-11-18 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_create_crud_b_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='create_crud_c_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('discription', models.CharField(max_length=300)),
            ],
        ),
    ]
