# Generated by Django 5.2.8 on 2025-11-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_create_crud_c_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='create_crud_d_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=50)),
                ('person_emailid', models.EmailField(max_length=100)),
            ],
        ),
    ]
